-- ==============================================================================
-- YooDeeHomeCare: Hospital Proximity & Healthcare Network Schema
-- ==============================================================================
-- 1. Table: hospitals (Master Data โรงพยาบาลทั่วประเทศ)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.hospitals (
    id VARCHAR(50) PRIMARY KEY,
    name_th VARCHAR(255) NOT NULL,
    name_en VARCHAR(255),
    hospital_type VARCHAR(50) NOT NULL DEFAULT 'รัฐบาล', -- 'รัฐบาล' / 'เอกชน'
    level VARCHAR(100), -- เช่น 'ตติยภูมิ / ศูนย์ความเป็นเลิศ', 'ทุติยภูมิ', 'ปฐมภูมิ'
    province VARCHAR(100) NOT NULL,
    district VARCHAR(100),
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    emergency_24h BOOLEAN DEFAULT true,
    google_maps_url VARCHAR(500),
    phone VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_hospitals_province ON public.hospitals (province);
CREATE INDEX IF NOT EXISTS idx_hospitals_name_th ON public.hospitals (name_th);
CREATE INDEX IF NOT EXISTS idx_hospitals_coords ON public.hospitals (latitude, longitude);

-- ==============================================================================
-- 2. Table: center_nearby_hospitals (ความสัมพันธ์ศูนย์ดูแล - โรงพยาบาลใกล้เคียง)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.center_nearby_hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_id BIGINT NOT NULL REFERENCES public.care_centers(id) ON DELETE CASCADE,
    hospital_id VARCHAR(50) NOT NULL REFERENCES public.hospitals(id) ON DELETE CASCADE,
    distance_km NUMERIC(6, 2) NOT NULL,
    is_primary_transfer BOOLEAN DEFAULT false,
    priority_order INT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_center_hospital UNIQUE (center_id, hospital_id)
);

CREATE INDEX IF NOT EXISTS idx_cnh_center_id ON public.center_nearby_hospitals (center_id);
CREATE INDEX IF NOT EXISTS idx_cnh_hospital_id ON public.center_nearby_hospitals (hospital_id);
CREATE INDEX IF NOT EXISTS idx_cnh_priority ON public.center_nearby_hospitals (center_id, priority_order);

-- ==============================================================================
-- 3. Row Level Security (RLS) Configuration
-- ==============================================================================
ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.center_nearby_hospitals ENABLE ROW LEVEL SECURITY;

-- Public Read สำหรับข้อมูลที่แสดงผลหน้าเว็บ
DROP POLICY IF EXISTS "Public Read hospitals" ON public.hospitals;
CREATE POLICY "Public Read hospitals" ON public.hospitals FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read center_nearby_hospitals" ON public.center_nearby_hospitals;
CREATE POLICY "Public Read center_nearby_hospitals" ON public.center_nearby_hospitals FOR SELECT USING (true);
