-- ==============================================================================
-- YooDeeHomeCare Database Schema for Supabase PostgreSQL
-- ==============================================================================
-- วิธีใช้งาน:
-- 1. เข้าสู่ Supabase Dashboard (https://supabase.com/dashboard)
-- 2. เลือกโปรเจกต์ของคุณ -> ไปที่แท็บ "SQL Editor" ด้านซ้าย
-- 3. วางโค้ด SQL ด้านล่างนี้ทั้งหมดแล้วกดปุ่ม "Run" (หรือคลิก Ctrl + Enter)
-- ==============================================================================

-- 1. ตาราง care_centers (ศูนย์ดูแลผู้สูงอายุ / ผู้ป่วย)
CREATE TABLE IF NOT EXISTS public.care_centers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT DEFAULT '',
    province TEXT DEFAULT '',
    lat NUMERIC DEFAULT 0,
    lng NUMERIC DEFAULT 0,
    price NUMERIC DEFAULT 0,
    type TEXT DEFAULT 'both', -- 'daily', 'monthly', 'both'
    rating NUMERIC DEFAULT 5,
    phone TEXT DEFAULT '',
    website TEXT DEFAULT '',
    map_url TEXT DEFAULT '',
    image_urls JSONB DEFAULT '[]'::jsonb,
    description TEXT DEFAULT '',
    services JSONB DEFAULT '[]'::jsonb,
    packages JSONB DEFAULT '[]'::jsonb,
    room_types JSONB DEFAULT '[]'::jsonb,
    has_government_certificate BOOLEAN DEFAULT false,
    brand_name TEXT DEFAULT '',
    brand_logo_url TEXT DEFAULT '',
    is_partner BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'visible', -- 'visible', 'hidden', 'pending'
    utm_source TEXT DEFAULT '',
    utm_medium TEXT DEFAULT '',
    utm_campaign TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_care_centers_status ON public.care_centers (status);
CREATE INDEX IF NOT EXISTS idx_care_centers_province ON public.care_centers (province);

-- 2. ตาราง blogs (บทความ)
CREATE TABLE IF NOT EXISTS public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    content TEXT DEFAULT '',
    excerpt TEXT DEFAULT '',
    cover_image TEXT DEFAULT '',
    author TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    tags JSONB DEFAULT '[]'::jsonb,
    is_published BOOLEAN DEFAULT true,
    is_recent BOOLEAN DEFAULT false,
    is_featured BOOLEAN DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_blogs_slug ON public.blogs (slug);
CREATE INDEX IF NOT EXISTS idx_blogs_is_published ON public.blogs (is_published);

-- 3. ตาราง consultations (คำขอปรึกษา / นัดหมาย)
CREATE TABLE IF NOT EXISTS public.consultations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    email TEXT DEFAULT '',
    line_id TEXT DEFAULT '',
    contact_name TEXT DEFAULT '',
    recipient_name TEXT DEFAULT '',
    recipient_age NUMERIC DEFAULT 0,
    relationship_to_recipient TEXT DEFAULT '',
    branch TEXT DEFAULT '',
    budget TEXT DEFAULT '',
    room_type TEXT DEFAULT '',
    convenient_time TEXT DEFAULT '',
    message TEXT DEFAULT '',
    status TEXT DEFAULT 'pending',
    submitted_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_consultations_status ON public.consultations (status);

-- 4. ตาราง contacts (ข้อความติดต่อเรา)
CREATE TABLE IF NOT EXISTS public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT '',
    email TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    subject TEXT DEFAULT '',
    message TEXT DEFAULT '',
    status TEXT DEFAULT 'unread',
    submitted_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 5. ตาราง admins (ผู้ดูแลระบบ)
CREATE TABLE IF NOT EXISTS public.admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    email TEXT DEFAULT '',
    full_name TEXT DEFAULT '',
    role TEXT DEFAULT 'admin', -- 'super_admin' or 'admin'
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    last_login TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_admins_username ON public.admins (username);

-- 6. ตาราง ads (โฆษณา / แบนเนอร์)
CREATE TABLE IF NOT EXISTS public.ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    link_url TEXT DEFAULT '',
    title TEXT DEFAULT '',
    description TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 7. ตาราง provider_signups (ใบสมัครผู้ให้บริการ)
CREATE TABLE IF NOT EXISTS public.provider_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    center_name TEXT DEFAULT '',
    owner_name TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    email TEXT DEFAULT '',
    line_id TEXT DEFAULT '',
    address TEXT DEFAULT '',
    subdistrict TEXT DEFAULT '',
    district TEXT DEFAULT '',
    province TEXT DEFAULT '',
    postal_code TEXT DEFAULT '',
    center_type TEXT DEFAULT '',
    capacity TEXT DEFAULT '',
    services TEXT DEFAULT '',
    description TEXT DEFAULT '',
    status TEXT DEFAULT 'pending'
);

-- 8. ตาราง traffic (บันทึกการเข้าชม / วิเคราะห์ UTM)
CREATE TABLE IF NOT EXISTS public.traffic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    event_type TEXT DEFAULT 'page_view',
    page_path TEXT DEFAULT '/',
    center_id NUMERIC,
    center_name TEXT DEFAULT '',
    utm_source TEXT DEFAULT '',
    utm_medium TEXT DEFAULT '',
    utm_campaign TEXT DEFAULT '',
    referrer TEXT DEFAULT '',
    user_agent TEXT DEFAULT '',
    ip TEXT DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_traffic_timestamp ON public.traffic (timestamp);

-- ==============================================================================
-- 9. Setup Storage Bucket for Images (yoodee-images)
-- ==============================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('yoodee-images', 'yoodee-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- นโยบายเปิดให้ทุกคนอ่านรูปภาพใน bucket ได้โดยตรง (Public Read)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND policyname = 'Public Access for yoodee-images'
    ) THEN
        CREATE POLICY "Public Access for yoodee-images"
        ON storage.objects FOR SELECT
        USING ( bucket_id = 'yoodee-images' );
    END IF;
END $$;

-- นโยบายอนุญาตให้อัปโหลดรูปภาพลง bucket ได้
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND policyname = 'Allow Uploads for yoodee-images'
    ) THEN
        CREATE POLICY "Allow Uploads for yoodee-images"
        ON storage.objects FOR INSERT
        WITH CHECK ( bucket_id = 'yoodee-images' );
    END IF;
END $$;

-- นโยบายอนุญาตให้ลบหรือแก้ไขรูปภาพใน bucket ได้
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND policyname = 'Allow Delete for yoodee-images'
    ) THEN
        CREATE POLICY "Allow Delete for yoodee-images"
        ON storage.objects FOR DELETE
        USING ( bucket_id = 'yoodee-images' );
    END IF;
END $$;

-- ==============================================================================
-- 10. สร้าง Super Admin คนแรกเริ่มต้น
-- Username: admin
-- Password: Admin@123456
-- (แนะนำให้เปลี่ยนรหัสผ่านทันทีหลังเข้าสู่ระบบครั้งแรก)
-- ==============================================================================
INSERT INTO public.admins (username, password, email, full_name, role, is_active, created_at)
VALUES (
    'admin',
    '$2b$10$cFwaqMib1cA5qGAROqtw5OOe1nQ9eE84vZP/kSOCilFm1lVuNn4Y.',
    'admin@yoodee.com',
    'Super Administrator',
    'super_admin',
    true,
    timezone('utc'::text, now())
)
ON CONFLICT (username) DO NOTHING;

-- ==============================================================================
-- 11. Row Level Security (RLS) Configuration
-- ==============================================================================
-- เปิด RLS สำหรับตารางทั้งหมดเพื่อความปลอดภัยสูงสุด
ALTER TABLE public.care_centers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_signups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.traffic ENABLE ROW LEVEL SECURITY;

-- นโยบาย Public Read สำหรับข้อมูลที่แสดงหน้าเว็บ
CREATE POLICY "Public Read care_centers" ON public.care_centers FOR SELECT USING (true);
CREATE POLICY "Public Read blogs" ON public.blogs FOR SELECT USING (true);
CREATE POLICY "Public Read ads" ON public.ads FOR SELECT USING (true);

-- นโยบาย Public Insert สำหรับฟอร์มหน้าเว็บที่ผู้ใช้กรอกเข้ามา
CREATE POLICY "Public Insert consultations" ON public.consultations FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Insert contacts" ON public.contacts FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Insert provider_signups" ON public.provider_signups FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Insert traffic" ON public.traffic FOR INSERT WITH CHECK (true);

-- Backend API Routes ใช้ SUPABASE_SERVICE_ROLE_KEY ซึ่งจะ bypass RLS อัตโนมัติอยู่แล้ว
-- จึงสามารถ SELECT, INSERT, UPDATE, DELETE ได้อย่างสมบูรณ์แบบและปลอดภัย
